spring:
  datasource:
    url: jdbc:h2:mem:foodies_application
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console.enabled:  true
server:
  port: 8082
 